apiVersion: v1
kind: Pod
metadata:
  name: k6-pvc-copy
spec:
  volumes:
    - name: k6-pvc-copy-storage
      persistentVolumeClaim:
        claimName: k6-runner-tests
  containers:
    - name: k6-pvc-copy-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/test"
          name: k6-pvc-copy-storage
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "100m"
          memory: "100Mi"
