name: Search data generation

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version tag'
        default: 'v1.0.0'
        required: true

permissions:
  contents: write

jobs:
  build:

    runs-on: [self-hosted, platform]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies and run generation
      run: |
        python3 -m venv test_env
        source test_env/bin/activate
        pip install pipenv
        cd search/data-generation
        pipenv install
        python3 -m pip install elasticsearch
        echo "###################### installed pipenv dependencies"
        cd ../..
        python3 search/data-generation/real-query-generator.py    
