# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version tag'
        default: 'v1.0.0'
        required: true

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python3 -m venv test_env
        source test_env/bin/activate
        pip install pipenv
        cd search/data-generation
        pipenv install
        echo "###################### installed pipenv dependencies"
        cd ../..
    - name: Generate files
      run: |
        python search/data-generation/real-query-generator.py
