name: Search data generation

on:
  workflow_dispatch:
    inputs:
      instances:
        description: 'Instances to generate data'
        default: 'zara'
        required: true
      languages:
        description: 'Languages to generate data'
        default: 'en_GB'
        required: true
      endpoints:
        description: 'Endpoints to generate data'
        default: 'search'
        required: true
      generation-mode:
        description: 'Target of the data generated'
        type: choice
        options:
        - saas
        - platform

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.SUPPORT_TOKEN }}
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies and run generation
      run: |
        python3 -m venv test_env
        source test_env/bin/activate
        pip install pipenv
        cd search/data-generation
        pipenv install
        python3 -m pip install elasticsearch
        cd ../..
    - name: Replace environment variables
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "INSTANCES=*"
        replace: "INSTANCES=${{ github.event.inputs.instances }}"
        include: "**options.ini"
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automatically generated search dataset
        file_pattern: '*.json'
